CREATE TABLE FUNC(
    ID_FUNC     INTEGER,
    NOME_FUNC   VARCHAR(40),
    ENDERECO    VARCHAR(40),
    CEP         VARCHAR(9),
    CIDADE      VARCHAR(20),
    UF          CHAR(2),
    TELEFONE    VARCHAR(15),
    ID_DEPART   INTEGER);

ALTER TABLE FUNC
ADD CONSTRAINT PK_FUNC PRIMARY KEY (ID_FUNC);

CREATE TABLE DEPART(
    ID_DEPART       INTEGER,
    NOME_DEPART     VARCHAR(40));

ALTER TABLE DEPART
ADD CONSTRAINT PK_DEPART PRIMARY KEY (ID_DEPART);

ALTER TABLE FUNC
ADD CONSTRAINT FK_DEPART FOREIGN KEY (ID_DEPART) REFERENCES DEPART (ID_DEPART);

ALTER TABLE FUNC
MODIFY ID_DEPART NUMBER(38) NOT NULL;

ALTER TABLE DEPART
DROP COLUMN ID_FUNC;

DESC DEPART

INSERT INTO DEPART(ID_DEPART, NOME_DEPART)
VALUES (70, 'ADMINISTRATIVO');

SELECT *
FROM DEPART;

INSERT INTO DEPART(ID_DEPART, NOME_DEPART)
VALUES (80, 'TI');

SELECT *
FROM DEPART;

ALTER TABLE DEPART
MODIFY NOME_DEPART VARCHAR(40) NOT NULL;

DESC DEPART

CREATE SEQUENCE sqCod
    MINVALUE 1
    MAXVALUE 300
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
INSERT INTO DEPART(ID_DEPART, NOME_DEPART)
VALUES (sqCod.nextval, 'RH');

SELECT *
FROM DEPART;

SELECT sqCod.NEXTVAL
FROM DUAL;

ALTER SEQUENCE sqCod
INCREMENT BY 1;